"""GBGPU's native constants come from lisaconstants (2026-10-08).

``src/gbgpu/cutils/lisaconstants_values.h`` is generated by LAT's
``lisatools.utils.lisaconstants_header`` (LISA.h / SharedMemoryGBGPU.cu and
the Detector.hpp / global.hpp copied from LAT include it); this checks the
committed copy against the installed lisaconstants, exactly.
"""
import os
import unittest

from lisatools.utils import lisaconstants_header as H

HEADER = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                      "src", "gbgpu", "cutils", "lisaconstants_values.h")


class LisaconstantsHeaderTest(unittest.TestCase):
    def test_committed_header_is_the_generated_one(self):
        with open(HEADER) as fh:
            text = fh.read()
        self.assertEqual(H.parse(text), H.expected_values())
        self.assertEqual(text, H.render())


if __name__ == "__main__":
    unittest.main()
